---
- hosts: all_hosts
  become: yes

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Remove Apache if present
      apt:
        name: apache2
        state: absent
        purge: yes

    - name: Install web server
      apt:
        name: "{{ web_package }}"
        state: present

    - name: Ensure web service is running
      service:
        name: "{{ web_service }}"
        state: started
        enabled: yes

    - name: Deploy dynamic website from template
      template:
        src: templates/index.html.j2
        dest: /var/www/html/index.html
        mode: "0644"
      notify: Restart web service

  handlers:
    - name: Restart web service
      service:
        name: "{{ web_service }}"
        state: restarted

